### PR TITLE
Update README.md

### LINKED ISSUE #2: Update README
- Describe the purpose of the project
- Describe how to contribute; code review process
- Describe build steps / system requirements / dependencies
- Links to documentation, mailing lists, community discussion forums, specification

### PR DESCRIPTION
**Pull request by JasonKeirstead**
Fixes #2 

Create a default initial readme describing the project

### CODE REVIEW

**Comment by davaya** [comment]
The goals as shown are:

> - To experiment and validate designs before codified in an architecture standard
> - To provide an example implementation in order to support the future testing of compliant vendor products.

The first is perfect.  The second is a perfect goal, but I have some concern with advertising this software as a first "example implementation" for compliance testing.   The prototype sends messages between the SCAPv2 architecture components over DXL topics as a way to illustrate the components and data flows.  But the messages themselves are purely for demonstration purposes, and are more like "Hello World" strings than first drafts of SCAPv2 data standards.

The prototype software is a great starting point for the communication framework.  We have more work to do on defining SCAPv2 data standards before we should even imply that it is a starting point for an example implementation.

**Comment by JasonKeirstead** [comment]
Hey Dave,

I lifted these statements from Charles' presentation. Am happy to change them to whatever you see fit. Do you want me to remove that one for now?

-
Jason Keirstead 
Distinguished Engineer, CTO - IBM Security Threat Management

Sent from my mobile device


   David Kemp --- [EXTERNAL] Re: [opencybersecurityalliance/scap-v2-prototype] Update README.md (#3) --- 
    From:"David Kemp" <notifications@github.com>To:"opencybersecurityalliance/scap-v2-prototype" <scap-v2-prototype@noreply.github.com>Cc:"Jason Keirstead" <jason.keirstead@ca.ibm.com>, "Author" <author@noreply.github.com>Date:Wed., Jan. 20, 2021 1:42 p.m.Subject:[EXTERNAL] Re: [opencybersecurityalliance/scap-v2-prototype] Update README.md (#3)
  
   
 The goals as shown are:   To experiment and validate designs before codified in an architecture standard To provide an example implementation in order to support the future testing of compliant vendor products.   
 The first is perfect. The second is a perfect goal, but I have some concern with advertising this software as a first "example implementation" for compliance testing. The prototype sends messages between the SCAPv2 architecture components over DXL topics as a way to illustrate the components and data flows. But the messages themselves are purely for demonstration purposes, and are more like "Hello World" strings than first drafts of SCAPv2 data standards. 
 The prototype software is a great starting point for the communication framework. We have more work to do on defining SCAPv2 data standards before we should even imply that it is a starting point for an example implementation.

**Comment by davaya** [comment]
I just don't want to create false expectations for the software as it stands today.  SCAPv2 will use SCAP data standards (XCCDF, OVAL, etc) in the OpenDXL messages, but the current software uses text strings and JSON data, so it can't be used as an interoperability test suite.   NIST will be working on the SCAPv2 data standards and welcome participation from all interested OCA members.  I'll be working on the information model (the abstract expression of XCCDF etc. that can be encoded in XML or JSON) and also welcome help from OCA.

**Comment by davaya** [comment]
Changes included in PR #4

**Pull request closed without merging**
